device: 'cuda'
seed: 1008
checkpoint_dir: 'output/'
checkpoint_epoch: 50
use_wandb: True
visualize: True

data:
  mode: ['all']

model:
  n_head: 4
  n_layers: 4
  d_model: 128
  d_rnn: 256
  d_inner: 512
  d_k: 64
  d_v: 64
  dropout: 0.1
  num_processes: 3
  p_init_random: True
  oracle: False
  split_loss: True
  loss_mode: ['bp', 'type']

train:
  lr: 0.001
  batch_size: 64
  smooth: 0
  epoch: 100
  bp_start_epoch: 20